server:
  port: 7074
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ashokit_ecomm
    username: root
    password: mysql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    rest:
      base-path: /api4
        
  boot:
   admin:
     client:
       url: http://localhost:1111/
  
  mail:
    host: smtp.gmail.com
    port: 587
    username: srinivas.gowdav5@gmail.com
    password: eeehndbsalfguulb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
management:
  endpoints:
    web:
     exposure:
       include: '*'
